name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install haveged for entropy
      run: sudo apt-get install haveged
    - name: Run tests
      run: sbt test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
